### ISSUE TITLE
Indented/sass format seems to be supported?

### ISSUE THREAD

**Issue by edemaine** [Meteor-Community-Packages/meteor-scss#297]
I am confused by this statement in the README:
> Note that due to a limitation in libsass, there is no support for indented sass syntax. This syntax is deprecated and will likely not ever get supported

I just tried using an indented-format `.sass` file in my Meteor project, and it worked fine (other than minor bugs in the libsass implementation). Is it possible that this sentence is out of date?

Also, as far as I can tell, [the indented/sass syntax is not deprecated](http://thesassway.com/news/sass-is-here-to-stay). I understand that libsass is deprecated, but libsass does support indented/sass syntax (with some minor bugs).

`meteor` version: 1.11.1

`fourseven:scss` version: 4.12.0

**Comment by sebakerckhof** [comment]
The problem is that it doesn't work together with a custom importer (like `fourseven:scss` does): https://github.com/sass/node-sass/issues/1192 . So imports of indented-syntax will fail.

You are right though that indented syntax is not deprecated, that was a misunderstanding from my side.
However, since libsass is deprecated, I'm working on a version with dart-sass which should fix:
- indented syntax imports
- some edge cases with imports (libsass doesn't give enough information to know to which file in the import tree it backtracks in some situations: https://github.com/sass/node-sass/issues/1188 )

However, I ran into some dart-sass issues which are blocking for a release at the moment: https://github.com/sass/dart-sass/issues/1138

**Comment by edemaine** [comment]
Ah, OK, so indented sass works "at the top level" (imported from a js file, for example), but not imported from sass or scss. That makes more sense. Do you want to edit the README to document this current state better, or should I submit a PR?

Looking forward to the dart-sass port! Looks like the bug is being processed at least...

**Comment by sebakerckhof** [comment]
Ah yes, I intended to update the readme and then got distracted 5 seconds after 😅. It's changed now. Thanks for the heads up.

**Comment by edemaine** [comment]
Thanks for fixing the README, and for the quick responses!
